#include "RemoteConnection/Message/MessageHeader/MessageHeaderInitialListOfPublishedAndSubscribedChannels.hpp"

REGISTER_SERIALIZATION(claid::RemoteConnection::MessageHeaderInitialListOfPublishedAndSubscribedChannels)