#include "RemoteConnection/Message/MessageHeader/MessageHeaderInitialListOfPublishedAndSubscribedChannels.hpp"

REGISTER_SERIALIZATION(portaible::RemoteConnection::MessageHeaderInitialListOfPublishedAndSubscribedChannels)