#include "RemoteConnection/Message/MessageHeader/MessageHeaderInitialListOfPublishedAndSubscribedChannels.hpp"

SERIALIZATION(portaible::RemoteConnection::MessageHeaderInitialListOfPublishedAndSubscribedChannels)